'use client';

import FadeUp from '@/components/animations/FadeUp';

interface CardData {
  icon: string;
  iconColor: string;
  title: string;
  description: string;
  bg: string;
}

const cards: CardData[] = [
  {
    icon: 'verified',
    iconColor: 'text-primary',
    title: 'Uncompromising Quality',
    description:
      'Strict adherence to ISO 3632 standards. Every batch is lab-tested for its safranal, crocin, and picrocrocin levels.',
    bg: 'bg-surface-container-low',
  },
  {
    icon: 'groups',
    iconColor: 'text-secondary',
    title: 'Community First',
    description:
      'We provide fair wages that are 30% higher than the market average, empowering women in the East Taliouine region.',
    bg: 'bg-surface-container-high',
  },
  {
    icon: 'eco',
    iconColor: 'text-primary',
    title: 'Organic Stewardship',
    description:
      'Zero chemical pesticides. We use ancestral composting techniques that honor the earth\u2019s natural rhythms.',
    bg: 'bg-surface-container-low',
  },
];

export default function SustainabilityCards() {
  return (
    <section className="bg-surface min-h-screen flex items-center py-32">
      <div className="mx-auto max-w-content px-[clamp(1.25rem,5vw,6rem)]">
        {/* Header */}
        <div className="mb-16 text-center">
          <FadeUp>
            <p className="mb-4 text-xs font-semibold uppercase tracking-[0.4em] text-primary">
              Our Promise
            </p>
          </FadeUp>
          <FadeUp delay={0.1}>
            <h2 className="font-headline text-h2 font-light italic text-on-surface">
              Sustainability &amp; The Circle of Life
            </h2>
          </FadeUp>
          <FadeUp delay={0.2}>
            <p className="mx-auto mt-4 max-w-xl font-light leading-relaxed text-on-surface-variant">
              Our cooperative ensures that the wealth generated by the &lsquo;Red Gold&rsquo; returns directly to the families of Taliouine, funding education and
              water conservation projects.
            </p>
          </FadeUp>
        </div>

        {/* Cards */}
        <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
          {cards.map((card, index) => (
            <FadeUp key={card.title} delay={0.1 * index}>
              <div
                className={`flex flex-col items-center rounded-sm p-10 text-center transition-transform duration-300 hover:-translate-y-1 ${
                  card.bg
                } ${index === 1 ? 'md:-translate-y-2' : ''}`}
              >
                {/* Icon circle */}
                <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-full border border-outline-variant">
                  <span
                    className={`material-icons-outlined text-3xl ${card.iconColor}`}
                  >
                    {card.icon}
                  </span>
                </div>

                <h3 className="font-headline text-xl font-light text-on-surface">
                  {card.title}
                </h3>

                <p className="mt-4 text-sm font-light leading-relaxed text-on-surface-variant">
                  {card.description}
                </p>
              </div>
            </FadeUp>
          ))}
        </div>
      </div>
    </section>
  );
}
